########## Example 1: DEX Volume ##########
[dune_queries.dex_volume]
query = "https://dune.com/queries/4388"
primary_key = ["project", "_col1"]
write_disposition = "merge"

##### Example 2: DEX Volume With Incremental #####
[dune_queries.dex_volume_incremental]
query = "https://dune.com/queries/4778954"
primary_key = ["project", "date"]
write_disposition = "merge"
replication_key = "date" # make sure the name of the param in dune query matches
starting_replication_value = "2025-01-01"

