########## Example 1: DEX Volume ##########
[dune_queries.dex_volume]
query = "https://dune.com/queries/4388"
primary_key = ["project", "_col1"]
write_disposition = "merge"

##### Example 2: DEX Volume With Incremental #####
[dune_queries.dex_volume_incremental]
query = "https://dune.com/queries/4778954"
primary_key = ["project", "date"]
write_disposition = "merge"
replication_key = "date" # make sure the name of the param in dune query matches name of the replication key
starting_replication_value = "2025-01-01"

##### Example 3: Custom SQL #####
[dune_queries.custom_sql]
query = """
SELECT
    timestamp,
    blockchain,
    contract_address,
    symbol,
    price
FROM prices.day
WHERE symbol = 'BRETT'
AND blockchain = 'base'
-- Must use 'replication_key' and 'cursor_value' keywords for incremental loading
AND {replication_key} > TIMESTAMP '{cursor_value}'
order by timestamp
"""
primary_key = "timestamp"
write_disposition = "merge"
replication_key = "timestamp"
starting_replication_value = "2024-11-01"





